create unit services
haite4/rentzila pull request #10
Opened 2024-10-21 18:47 UTC by haite4

2024-10-25 12:49 UTC, AndreyCar commented on tests/createUnitServices.spec.ts
> +      await createUnitPage.getMapPopUp().waitFor({ state: "visible" });
Use expect.toBeVisible() instead of locator.waitFor()

2024-10-25 12:49 UTC, AndreyCar requested changes
.

2024-10-26 10:47 UTC, haite4 commented on data/general_msg.json
> +  "empty": "",
Not necessarily, but I've started using this approach to keep all messages in a json file

2024-10-30 07:15 UTC, AndreyCar approved these changes

2024-10-30 09:55 UTC, merged