Tests
haite4/rentzila pull request #5
Opened 2024-09-17 12:08 UTC by haite4

Made 4 automated tests for rentzila website main page

2024-09-25 12:37 UTC, DenysT07 requested changes

2024-09-25 12:37 UTC, DenysT07 commented on pages/main.page.ts
Не використовуй локатори із згенерованими частинами.
Не використовувати тут this.page а юзати методи з базового пейджа.

2024-09-25 12:37 UTC, DenysT07 commented on pages/main.page.ts
> +  async getLocatorOfEquipmentTab(): Promise<Locator[]> {
Замість цього всього можна написати один xpath локатор і з його допомогою повернути масив елементів

2024-09-25 12:37 UTC, DenysT07 commented on pages/products-details.page.ts
> + async  getUnitCharacteristicText(){
Подумай як тут переписати так щоб видалити FOR

2024-09-25 12:37 UTC, DenysT07 commented on pages/products.page.ts
Не використовуй локатори із згенерованими частинами.
Не використовувати тут this.page а юзати методи з базового пейджа.

2024-09-25 12:37 UTC, DenysT07 commented on pages/products.page.ts
> +    return await this.page.getByText(text).nth(1).textContent();
Після return не треба ставити await

2024-09-25 12:37 UTC, DenysT07 commented on pages/products.page.ts
> +      (await this.page.locator(expandedClassSelector).count()) > 0;
Прибрати порівняння кількості, знайти метод по типу .isExist()

2024-09-25 12:37 UTC, DenysT07 commented on pages/products.page.ts
> +  async getProductQuantity(text):Promise<string>{
Визнач тип для тексту і видали IF

2024-09-25 12:37 UTC, DenysT07 commented on pages/products.page.ts
> +  async getProductQuantity(text):Promise<string>{
А ще краще перенеси його в helper і назви getDigits

2024-09-25 12:37 UTC, DenysT07 commented on playwright.config.ts
> +  workers: process.env.CI ? 1 : undefined,
Чому тут undefined?

2024-09-25 12:37 UTC, DenysT07 commented on tests/consultationForm.spec.ts
> +      "rgb(247, 56, 89)"
Всі кольори можна закинути у ENUM окремий

2024-09-25 12:37 UTC, DenysT07 commented on tests/consultationForm.spec.ts
> +    for (let i = 0; i < 2; i++) {
навіщо тут цикл?

2024-09-25 12:37 UTC, DenysT07 commented on tests/footer.spec.ts
> +    expect(mainPage.getLogoFooter().isDisabled()).toBeTruthy();
використати перевірку toBeDisabled()
Чому немає await?

2024-09-25 12:37 UTC, DenysT07 commented on tests/main.spec.ts
> +        try {
Через чей try catch тест взагалі не показує що він не проходить

2024-09-25 12:37 UTC, DenysT07 commented on helpers/api_helper.ts
> +  isPhoneNumbePresent(feedbackList: any[], phoneNumber: string): boolean {
Або винеси чей метод в хелпер, або викликати запит цим методом

2024-09-25 12:37 UTC, DenysT07 commented on helpers/api_helper.ts
> +  async createJwtToken() {
І зроби цей метод private

2024-09-26 16:21 UTC, haite4 commented on tests/main.spec.ts
> +        try {
Цей try catch написав тому що в рентзіла не всі юніти є  і тест ломався кожний раз. Питав ментора він сказав щоб залишив так.

2024-10-02 15:02 UTC, DenysT07 commented on pages/page.ts
> +const logo = `[data-testid="logo"]`;
В основній пейджі не має бути локаторів

2024-10-02 15:04 UTC, DenysT07 commented on pages/page.ts
Трохи дивне форматування, десь є крапка з комою а десь немає, це стосцується всіх файлів

2024-10-02 15:09 UTC, DenysT07 commented on tests/footer.spec.ts
> +    expect(mainPage.getTenderSearchInput()).toHaveAttribute(
await

2024-10-02 15:12 UTC, DenysT07 commented on tests/main.spec.ts
> +        try {
Якщо тест фейлиться, він має показати це. Перед циклом створи ерей який буде зберігати помилки з кетч блоку і після проходженя циклу чи він пустий, якщо ні - тоді фейлитись

2024-10-02 18:12 UTC, haite4 commented on helpers/random_value.ts
> +import { faker as faker_uk } from "@faker-js/faker/locale/uk"
Мені потрібен  український номер телефону,  а  також якщо я буду тільки використовувати faker_uk  то такі метои як firstName і тд не будуть доступні для укр локації. Із-за цього використовую два імпорта

2024-10-09 12:07 UTC, DenysT07 approved these changes

2024-10-14 17:35 UTC, merged